service: crud-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  apiName: ${self:service}
  memorySize: 128
  timeout: 10

functions:
  create:
    handler: src/handler.create
    events:
      - http:
          path: products
          method: POST
          cors: true
  
  listAll:
    handler: src/handler.listAll
    events:
      - http:
          path: products
          method: GET
          cors: true

  listOne:
    handler: src/handler.listOne
    events:
      - http:
          path: products/{id}
          method: GET
          cors: true

  edit:
    handler: src/handler.edit
    events:
      - http:
          path: products/{id}
          method: PUT
          cors: true

  deleteOne:
    handler: src/handler.deleteOne
    events:
      - http:
          path: products/{id}
          method: DELETE
          cors: true

plugins:
- serverless-offline